---

- hosts: all
  become: true
  pre_tasks:


  - name: Install updates (Rocky)
    tags: always               
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      only_upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php package for ubuntu server
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html files for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644




  - name: install apache and php for Rocky servers
    tags: apache,rocky,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky" 


- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package (Rocky)
    tags: rocky,db,mariadb
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
# - name: Start httpd
#    service:
#      name: httpd
#      state: started
#      enabled: yes



